### ISSUE TITLE
Why is it impossible to set parameters with MakesHttpRequest->json()?

### ISSUE THREAD

**Issue by HenkPoley** [albertcht/lumen-testing#13]
I want do something like this in my test:

```php
$this->json('GET', '/something?var=x'); // Doesn't work, even in vanilla Lumen
$this->json('GET', '/something', ['var' => 'x']); // Should also work in AlbertCht/lumen-testing, but doesn't
```

This doesn't work, so I went looking what's happening.

In the end `->json()` does:

```php
        return $this->call(
            $method, $uri, [], [], $files, $this->transformHeadersToServerVars($headers), $content
        );
```

Where the first `[]` sets `$parameters` on `call()`. Meaning, by default I cannot send parameters to a JSON request (?)

I keep bumping in that my Validator says that a required variable is not set (`validation.required`)

Lumen 5.8.13
albertcht/lumen-testing v1.1
PhpUnit 7.5.18

NB: For now I'm attempting to switch to Lumen's built-in testing. Since this is a blocker for me.

**Comment by HenkPoley** [comment]
With a colleague we traced through, and within `src/Concerns/RoutesRequests.php->sendThroughPipeline` it creates a new Request (`$this->make('request')`), which does not contain the variables ('parameters') I need anymore.

This function is called from `RoutesRequests->dispatch()` which still has the variables/parameters.

I suspect in newer Laravel you need to 'announce' / 'attach' these parameters, so when it makes a new request it knows what to put into the request.

For ease of tracing up to there, here's a mangled backtrace up to that point:
```
  string(48) "Laravel\Lumen\Application .. sendThroughPipeline"
  [42]=>
  string(37) "Laravel\Lumen\Application .. dispatch"
  [43]=>
  string(35) "Laravel\Lumen\Application .. handle"
  [44]=>
  string(40) "AlbertCht\Lumen\Testing\TestCase .. call"
  [45]=>
  string(40) "AlbertCht\Lumen\Testing\TestCase .. json"
  [46]=>
  string(37) "PackageOptionsTest .. testBasicIdRead"
  [47]=>
  string(37) "PHPUnit\Framework\TestCase .. runTest"
  [48]=>
  string(37) "PHPUnit\Framework\TestCase .. runBare"
  [49]=>
  string(35) "PHPUnit\Framework\TestResult .. run"
  [50]=>
  string(33) "PHPUnit\Framework\TestCase .. run"
  [51]=>
  string(34) "PHPUnit\Framework\TestSuite .. run"
  [52]=>
  string(34) "PHPUnit\TextUI\TestRunner .. doRun"
  [53]=>
  string(29) "PHPUnit\TextUI\Command .. run"
  [54]=>
  string(30) "PHPUnit\TextUI\Command .. main"
```

The difference from running the same in vanilla Lumen testing framework, is literally that these are not your code:

```
  [44]=>
  string(38) "Laravel\Lumen\Testing\TestCase .. call"
  [45]=>
  string(38) "Laravel\Lumen\Testing\TestCase .. json"
```

`Laravel\Lumen\Testing\TestCase` or your `AlbertCht\Lumen\Testing\TestCase` get decorated with each own's `MakesHttpRequests`, from which `function json()` differs on line 1 (`$files = $this->extractFilesFromDataArray($data);` is not in Lumen). This line does exist in the full Laravel, and it doesn't seem related, so we haven't traced that path.

The next call (above that, so `[44]`) in the AlbertCht version it does not do ` $this->app['request'] = LumenRequest::createFromBase($symfonyRequest);`. So I just commented out the last 5 lines, and copied the last 4 lines of vanilla Lumen's version. ~~This _seems_ to fix my bug !~~. Now I get the parameters I need in the `Request $request` inside my Controller. But it appears the response is no longer decorated with all the nice extra stuff (such as `->assertJson()`). So I'll have to do some more digging.

Edit: Ah, doh, if your comment out `$this->response = $this->createTestResponse($response);`, the Response is not decorated the all the nice testing stuff.

**Comment by HenkPoley** [comment]
Summarizing:

1. Go to this code: https://github.com/albertcht/lumen-testing/blob/64167bc0fd2ca85f0b501ed2b5976aeb75a1316a/src/Concerns/MakesHttpRequests.php#L342
2. Pull out `Request::createFromBase($symfonyRequest)` into a variable called `$this->app['request']`.
3. Profit!

PR here: https://github.com/albertcht/lumen-testing/pull/14

**Comment by HenkPoley** [comment]
For reference, `$this->app['request']` was introduced in Lumen 5.8: https://github.com/laravel/lumen-framework/blob/5.6/src/Testing/Concerns/MakesHttpRequests.php

**Comment by HenkPoley** [comment]
For reference, `$this->app['request']` was introduced in Lumen 5.8: https://github.com/laravel/lumen-framework/blob/e6f63430c351a7fc0662b26dea02e0add67d769d/src/Testing/Concerns/MakesHttpRequests.php#L338

Maybe we should add a test for AlbertCht/lumen-testing that this works as expected.

**Comment by HenkPoley** [comment]
It remains the case that under the normal webserver access to Lumen, in a `Middleware->handle($request, Closure $next)` you can do:
```php
$lang = $request->offsetGet('lang');
// Or:
$lang = $request->route('lang');
```

That breaks under PhpUnit. But I believe even under vanilla Lumen testing.

**Comment by albertcht** [comment]
Hi @HenkPoley ,

Thanks a lot for your detailed code trace and pull request! I will merge them soon.

**Comment by HenkPoley** [comment]
It would be nice if a new release was rolled to composer.

Current v1.1 prohibits me from testing with a fresh vendor folder.

And for some reason my  composer doesn't pull in dev-master.
