### ISSUE TITLE
Travis only tests for Lumen 5.3 to 5.6

### ISSUE THREAD

**Issue by HenkPoley** [albertcht/lumen-testing#15]
This misses Lumen 5.7 (september 2018), 5.8 and 6.x

**Comment by HenkPoley** [comment]
PR here: https://github.com/albertcht/lumen-testing/pull/16

**Comment by HenkPoley** [comment]
Ah cool, Travis now immediately detects once the tests have finished 👍

**Comment by albertcht** [comment]
I've merged that pull request. Really appreciated your work.
