### ISSUE TITLE
Problem with Lumen 5.6.4, application not bootstrapping/refreshing correctly after the first test.

### ISSUE THREAD

**Issue by jersak** [albertcht/lumen-testing#2]
We recently updated Lumen from 5.6.3 to 5.6.4 on a few of our applications and it seems it broke most of our tests. The first test runs correctly but after that it seems that the application is not bootstrapped correctly, showing a stacktrace similar to the following:

```
56) StatesFeatureTest::testGetInvalidStateByCountryId
Error: Call to undefined method Illuminate\Container\Container::basePath()

/home/vagrant/locations-api/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:191
/home/vagrant/locations-api/vendor/albertcht/lumen-testing/src/TestCase.php:46
/home/vagrant/locations-api/vendor/laravel/lumen-framework/src/Testing/TestCase.php:56
/home/vagrant/locations-api/vendor/laravel/lumen-framework/src/Testing/TestCase.php:67
/home/vagrant/locations-api/vendor/albertcht/lumen-testing/src/TestCase.php:24
```

Rolling back to Lumen 5.6.3 makes it work fine again.

We noticed that there was a change to the flush method on Application.php that might be related to this: https://github.com/laravel/lumen-framework/compare/v5.6.3...v5.6.4

**Comment by kaishounachi** [comment]
Also getting the same error in Lumen 5.5, PHP 7.1:
Error: Call to undefined method Illuminate\Container\Container::basePath()

**Comment by albertcht** [comment]
Hi @jersak and @kaishounachi ,

Thanks for your reports, I will check it in the next few days.

**Comment by albertcht** [comment]
Yes, I have confirmed that this bug will appear in Lumen 5.6.4. I will work on fixing this issue.

**Comment by albertcht** [comment]
Hi @jersak ,

This bug has been fixed in the release `v0.6`. You can upgrade your package to see if it works.

**Comment by Asmaasalem95** [comment]
The same error with lumen 6.0 and php 7.4 
Error: Call to undefined method Illuminate\Container\Container::basePath()

**Comment by zong0828** [comment]
Same issue with lumen 5.8 and php 7.2
Call to undefined method Illuminate\Container\Container::basePath()

**Comment by egerb** [comment]
Same fo Lumen 6.x and php 7.4

**Comment by nicopenaredondo** [comment]
hello. any update on this one ?
